resources:
  pipelines:
    airline_pipeline:
      name: ${bundle.target}-${var.student_name}-airline-pipeline
      catalog: ${var.catalog}
      schema: ${resources.schemas.project_schema.name}
      serverless: true
      continuous: false
      edition: ADVANCED
      channel: CURRENT
      photon: true
      libraries:
        - notebook:
            path: ../src/airline_pipeline.sql
      configuration:
        catalog: ${var.catalog}
        schema: ${resources.schemas.project_schema.name}
        student_name: ${var.student_name}
        source_table: ${var.source_table}
        cdc_volume_path: /Volumes/${var.catalog}/${resources.schemas.project_schema.name}/${resources.volumes.airline_cdc_volume.name}
      event_log:
        catalog: ${var.catalog}
        schema: ${resources.schemas.project_schema.name}
        name: airline_pipeline_event_log
      tags:
        project: governed-airline-performance
        student: ${var.student_name}
        environment: ${bundle.target}
