name: Deploy dev

on:
  push:
    branches: [dev]

permissions:
  contents: read

jobs:
  deploy-and-run:
    if: ${{ vars.CI_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    environment: dev
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      DATABRICKS_AUTH_TYPE: oauth-m2m
    steps:
      - uses: actions/checkout@v5
      - uses: databricks/setup-cli@main
      - run: databricks bundle validate -t development
      - run: databricks bundle deploy -t development
      - run: databricks bundle run -t development retail_job
