name: Deploy production

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy-and-run-production:
    if: ${{ vars.CI_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.DATABRICKS_CLIENT_SECRET }}
      DATABRICKS_AUTH_TYPE: oauth-m2m
    steps:
      - uses: actions/checkout@v5
      - uses: databricks/setup-cli@main
      - run: databricks bundle deploy -t production
      - run: databricks bundle run -t production retail_job
